### ISSUE TITLE
Query: Segmentation filter

### ISSUE THREAD

**Issue by nsheff** [databio/episb-hub#4] opened 2018-11-27 15:24 UTC
## Segmentation filter query

One  query type is a *segmentation filter*. The goal of this query type is to return a subset of a given segmentation, as determined by user-given conditions. For instance, we may want the subset of ~segments~ *regions* that have biological properties *x*, *y*, and *z*. 

To create this kind of query, the Hub UI provides a dynamic series of HTML input widgets that populate as information is added. We need to select a segmentation that the user wants to filter. One way this could work is: first, the user restricts the segmentation to those on the reference genome assembly of interest. The web GUI renders a dropdown, `Select genome`. User selects, *e.g.* `hg38`. This populates a second dropdown, `Select segmentation`. This is populated from the list of segmentations this hub knows about that segment the given reference assembly.

Once we have selected a single segmentation, we have narrowed down the data we can consider to the set of experiments that annotate that particular segmentation (which is specified in the provider design interface). We then show the user an "add condition" interface (similar to what you would see when building an email inbox filter rule). This interface is populated based on the available experiments defined in the design interface. The user can then specify any number of conditions, which can be things like:

- Value of ranged experiment `experiment1` must be "greater than 500".
- Value of binary experiment `experiment3` must be "True"

When the user is done assembling the desired list of conditions, she clicks `submit`. Conditions are translated into a query, which returns **the set of ~segments~ *regions* that meet all conditions**.

Ideally, this *segmentation filter* query is also possible to construct via a *POST* of a *json* document, so that someone could be an R/python interface to pull down the same queries. The result should be returnable either in [BED format](https://genome.ucsc.edu/FAQ/FAQformat.html#format1) or as a `JSON`.

**Comment by oddodaoddo** [comment] 2019-01-23 17:19
This should work with the latest commit (https://github.com/databio/episb-hub/commit/8101aeef8afdc13b2001d7d1a28ec4088c3c6079). Now I need to figure out the actual selectors on an experiment. What do we want to have here?

**Comment by nsheff** [comment] 2019-01-24 14:21
I can help with the presentation part pretty easily -- I think your primary goal is to get the functionality working and don't worry too much about the presentation at this point. is it functional now? Then I can take a look

**Comment by oddodaoddo** [comment] 2019-01-24 15:25
I added the capability to get the min/max range values for selected experiment and it is reflected in slider. I don't know how to make the slider slide between 0 and 1, it either goes to 0 or 1 if manipulated.

**Comment by oddodaoddo** [comment] 2019-01-24 17:58
@nsheff : I have spent a few hours trying to figure out how to add another filter control after pressing "Add rule" button but I am going to punt here and wait for some help. Any example/help welcome.

**Comment by aaron-gu** [comment] 2019-01-24 21:08
Hi Ognen, I'm an undergraduate with Nathan at UVA. I can help out the with the Segmentation filter frontend - I think it will need some JQuery for dynamic loading and adding rules.

**Comment by oddodaoddo** [comment] 2019-01-24 21:14
Sweet - go for it :smile:

**Comment by michalstolarczyk** [comment] 2019-01-24 21:55
> Hi Ognen, I'm an undergraduate with Nathan at UVA. I can help out the with the Segmentation filter frontend - I think it will need some JQuery for dynamic loading and adding rules.

You can see how it's done in `caravel` if you need. I'm using it in a few places

**Comment by oddodaoddo** [comment] 2019-01-24 22:02
Michal, thanks for the pointer! I will take a look at it :smile:

**Comment by aaron-gu** [comment] 2019-01-25 21:21
I implemented the add rule button. It works by giving the slider a name, and the corresponding <span> an HTML id with the same text as the slider name. @2140c55

**Comment by oddodaoddo** [comment] 2019-01-28 12:19
@aaron-gu : How are you testing the changes you made? If I run FLASK_APP="main.py" flask run - it just hangs ....

**Comment by aaron-gu** [comment] 2019-01-28 14:00
I ran them using the Dockerfile-dev and the command that I added to the README.

**Comment by oddodaoddo** [comment] 2019-01-28 14:07
Ok - my dev box is a FreeBSD machine and I do not have an easy way to run Docker containers on it. Let me see what it will take to run it without Docker.

**Comment by oddodaoddo** [comment] 2019-01-28 14:14
Can you try and figure out what change is making it hang when running without a container. I am thinking we should be able to run this every way possible since people who may want to contribute may not be able to (or want to) run Docker to do development. I think main.py was not touched in the last commit so it is something in templates/home.html javascript that is making it hang?

**Comment by nsheff** [comment] 2019-01-28 14:40
it is also hanging for me...

**Comment by nsheff** [comment] 2019-01-28 14:45
it's also hanging on the served version....

**Comment by nsheff** [comment] 2019-01-28 14:53
I don't think the hanging is due to @aaron-gu's changes though, because when I check out earlier commits I have the same issue. I can't really diagnose this, something strange is going on...

**Comment by nsheff** [comment] 2019-01-28 14:56
It is no longer hanging for me on the master branch. I think it has something to do with google analytics or some server or something...

**Comment by oddodaoddo** [comment] 2019-01-28 15:01
That's not good.

**Comment by oddodaoddo** [comment] 2019-01-28 15:05
It still hangs for me if I run "FLASK_APP="main.py" flask run" on my machine and try to go to localhost:5000

**Comment by aaron-gu** [comment] 2019-01-28 15:06
I just got on and found that it's hanging on the Docker container too. This didn't happen on Friday or Saturday. I'll look into the script tags to see if any one of them is causing the problem.

**Comment by oddodaoddo** [comment] 2019-01-28 15:06
Ok - I think it is hanging because provider.episb.org is hanging?

**Comment by oddodaoddo** [comment] 2019-01-28 15:11
Yup - confirmed - provider.episb.org is the culprit. @nmagee - did the machine reboot? I see uptime of 3 hours or so. I am guessing this borked elasticsearch and hence the episb provider? :smile:

**Comment by oddodaoddo** [comment] 2019-01-28 15:16
elastic container's overlay in /var/lib/docker/overlay is what is eating into the space because all elastic indices are stored there.

**Comment by oddodaoddo** [comment] 2019-01-28 15:27
I restarted episb provider container but we are down to the last 50M on / on the machine so.....

**Comment by nmagee** [comment] 2019-01-28 15:42
@oddodaoddo `docker image prune` is our friend -- I just got us 6.7GB back, though I realize that's not tons of space.

**Comment by nmagee** [comment] 2019-01-28 15:43
There is also 50GB+ available in the `/home` partition.

**Comment by oddodaoddo** [comment] 2019-01-28 16:01
@nmagee I think we should be stable for now with the reclaimed space you just provided :). I think at some point we need to sit down with @nsheff and decide on the move to actual production.

**Comment by nmagee** [comment] 2019-01-28 16:07
Agreed. And given that running any persistent storage for ES should mean *local* storage, I'm willing to rethink how I set up and deploy one of these 3 DC/OS storage nodes. They have it all -- tons of storage (128TB), CPU (48 cores), mem (376GB), and bandwidth (40Gbps), and so ES could live within the same IP space as everything running in DCOS.

**Comment by oddodaoddo** [comment] 2019-02-21 18:32
This [commit](https://github.com/databio/episb-hub/commit/74cbfce19a769a387972f4e36a08f7dbc21ad570) implements this feature. I am closing it since we have a separate issue - #35 - that refers to this work.

**Closed by oddodaoddo** 2019-02-21 18:32 UTC
Labels: help wanted, priority-high, query-type
